import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});


export const metadata = {
  title: "Biko-Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#fff8ee]">
        <Navbar></Navbar>
        <main >
          {children}
          <Toaster position="top-right" />
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
